name: Envio de Lembrete Diário
on:
  schedule:
    # 22:10 no horário de Brasília (BRT) = 01:10 UTC
    - cron: '10 1 * * *'
  workflow_dispatch: 

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22' # Atualizamos para a versão 22
          
      - name: Instalar bibliotecas
        run: npm install firebase-admin resend
        
      - name: Rodar script
        run: node scripts/send-emails.cjs # Mudamos para .cjs aqui
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
