name: Envio de Lembrete Diário
on:
  schedule:
    # 01:00 UTC é 22:00 no horário de Brasília (BRT)
    - cron: '10 1 * * *'
  workflow_dispatch: # Isso permite que você aperte um botão para testar agora!

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Instalar bibliotecas
        run: npm install firebase-admin resend
        
      - name: Rodar script
        run: node scripts/send-emails.js
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
